In [1]:
import numpy as np
import pandas as pd 


In [2]:
outlook = ["Sunny","Sunny","Overcast","Rain","Rain","Rain","Overcast","Sunny",
        "Sunny","Rain","Sunny","Overcast","Overcast","Rain"]

temperature = ["Hot","Hot","Hot","Mild","Cool","Cool","Cool","Mild","Cool","Mild","Mild","Mild","Hot","Mild"]
Humidity = ["High","High","High","High","Normal","Normal","Normal","High",
          "Normal","Normal","Normal","High","Normal","High"]

Wind = ["Weak","Strong","Weak","Weak","Weak","Strong","Strong","Weak",
      "Weak","Weak","Strong","Strong","Weak","Strong"]

Play = ["No","No","Yes","Yes","Yes","No","Yes","No",
         "Yes","Yes","Yes","Yes","Yes","No"]


In [3]:
#encoding
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
outlook_encoded=lab.fit_transform(outlook)
outlook_encoded

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [4]:
temp_encoder=lab.fit_transform(temperature)
temp_encoder

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [5]:
Humidity_encoder=lab.fit_transform(Humidity)
Humidity_encoder

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0])

In [6]:
wind_encoder=lab.fit_transform(Wind)
wind_encoder

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0])

In [7]:
#zip
feature=list(zip(outlook_encoded,temp_encoder,Humidity_encoder,wind_encoder))
feature

[(np.int64(2), np.int64(1), np.int64(0), np.int64(1)),
 (np.int64(2), np.int64(1), np.int64(0), np.int64(0)),
 (np.int64(0), np.int64(1), np.int64(0), np.int64(1)),
 (np.int64(1), np.int64(2), np.int64(0), np.int64(1)),
 (np.int64(1), np.int64(0), np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(0), np.int64(1), np.int64(0)),
 (np.int64(0), np.int64(0), np.int64(1), np.int64(0)),
 (np.int64(2), np.int64(2), np.int64(0), np.int64(1)),
 (np.int64(2), np.int64(0), np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(2), np.int64(1), np.int64(1)),
 (np.int64(2), np.int64(2), np.int64(1), np.int64(0)),
 (np.int64(0), np.int64(2), np.int64(0), np.int64(0)),
 (np.int64(0), np.int64(1), np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(2), np.int64(0), np.int64(0))]

In [8]:
#Model creation

#3 type of classifier
#Gaussian()
#Multinomial()
#Bernoulli()

#Gaussian() : continuous data

from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(feature,Play)
print(model.predict([[2,0,0,0]]))


['No']
